version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app/server
      - ./server/dao/storage:/app/server/dao/storage
    ports:
      - "8042:8000"

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app/client
    ports:
      - "3042:3000"
